// ==========================================
// SCHEMES & OPPORTUNITIES HUB DATASETS (SIH26136)
// Centralized Marketplace: Govt Schemes, Startup RFPs & Trust Engine
// ==========================================

export const CENTRAL_SCHEMES_DIRECTORY = [
  {
    id: 'sch_dpiit_sisfs',
    name: 'Startup India Seed Fund Scheme (SISFS)',
    agency: 'Department for Promotion of Industry and Internal Trade (DPIIT), MoCI',
    category: 'Grants & Equity Support',
    fundingType: 'Grant & Debt',
    budget: 'Up to ₹50 Lakhs',
    fundingAmountNum: 5000000,
    sector: 'Multi-Sector Innovation',
    stage: 'TRL 3 - TRL 6 (PoC to Prototype)',
    eligibility: 'DPIIT-recognized startup incorporated not more than 2 years ago, with a viable business idea demonstrating proof-of-concept.',
    benefits: 'Up to ₹20 Lakhs as grant for validation of PoC/prototype; up to ₹50 Lakhs via convertible debentures for commercialization.',
    deadline: '2026-11-30',
    applicationLink: 'https://seedfund.startupindia.gov.in',
    isOfficial: true,
    officialSource: 'DPIIT Startup India Portal (startupindia.gov.in)',
    lastVerified: '2026-09-01',
    status: 'Active'
  },
  {
    id: 'sch_dst_nidhi_prayas',
    name: 'DST NIDHI-PRAYAS (PRomoting and Accelerating Young and ASpiring innovators)',
    agency: 'Department of Science & Technology (DST), Govt of India',
    category: 'Prototype Grant & Lab Access',
    fundingType: 'Grant',
    budget: 'Up to ₹10 Lakhs',
    fundingAmountNum: 1000000,
    sector: 'DeepTech & Hardware',
    stage: 'TRL 4 - TRL 7 (Idea to Hardware Prototype)',
    eligibility: 'Individual innovators and early-stage startups with tangible technology ideas requiring fab-lab and fabrication access.',
    benefits: '100% grant-in-aid of up to ₹10 Lakhs, free access to PRAYAS Fab-Labs across IITs/NITs, and technical mentorship.',
    deadline: '2026-10-15',
    applicationLink: 'https://nidhi-prayas.org',
    isOfficial: true,
    officialSource: 'Department of Science and Technology (dst.gov.in)',
    lastVerified: '2026-08-20',
    status: 'Active'
  },
  {
    id: 'sch_msins_maha_grant',
    name: 'Maharashtra State Innovation Society (MSInS) Scaling Grant',
    agency: 'Skills, Employment, Entrepreneurship & Innovation Dept, Govt of Maharashtra',
    category: 'State Sandbox & Procurement Access',
    fundingType: 'Grant & Scale FastTrack',
    budget: 'Up to ₹15 Lakhs',
    fundingAmountNum: 1500000,
    sector: 'GovTech, HealthTech & AgriTech',
    stage: 'TRL 7 - TRL 8 (Operational Pilot)',
    eligibility: 'Maharashtra-incorporated or operating DPIIT startups with ready prototype suitable for state department deployment.',
    benefits: '₹15 Lakhs equity-free grant, direct sandbox pilot clearance at district civil hospitals or PWD corridors, and GFR 149 scale waiver.',
    deadline: '2026-10-31',
    applicationLink: 'https://msins.in/schemes/startup-week',
    isOfficial: true,
    officialSource: 'Maharashtra State Innovation Society (msins.in)',
    lastVerified: '2026-09-10',
    status: 'Active'
  },
  {
    id: 'sch_birac_big',
    name: 'BIRAC Biotechnology Ignition Grant (BIG - IMRB/DBT)',
    agency: 'Biotechnology Industry Research Assistance Council (BIRAC), Dept of Biotechnology',
    category: 'Biotech & Medical Grants',
    fundingType: 'Grant',
    budget: 'Up to ₹50 Lakhs',
    fundingAmountNum: 5000000,
    sector: 'HealthTech & BioTech',
    stage: 'TRL 4 - TRL 7 (Clinical PoC to Validation)',
    eligibility: 'Startups and researchers registered in India developing diagnostic devices, healthcare algorithms, or biomedical solutions.',
    benefits: '₹50 Lakhs non-dilutive grant over 18 months, clinical validation assistance at partner medical colleges, and regulatory pathway support.',
    deadline: '2026-11-15',
    applicationLink: 'https://birac.nic.in/big.php',
    isOfficial: true,
    officialSource: 'BIRAC Central Portal (birac.nic.in)',
    lastVerified: '2026-07-28',
    status: 'Active'
  },
  {
    id: 'sch_nasscom_deeptech',
    name: 'NASSCOM DeepTech Innovation & Corporate Connect',
    agency: 'NASSCOM Center of Excellence for IoT & AI',
    category: 'Mentorship & Incubation',
    fundingType: 'Incubation & Cloud Credits',
    budget: '₹25 Lakhs in Credits + Enterprise Access',
    fundingAmountNum: 2500000,
    sector: 'AI, IoT & Robotics',
    stage: 'TRL 6 - TRL 8 (Product Market Fit)',
    eligibility: 'Early growth AI/IoT startups with working beta deployment and IP ownership in India.',
    benefits: '$25,000 cloud infrastructure credits, direct demo days with Fortune 500 buyers, state government challenge fast-tracks.',
    deadline: '2026-12-15',
    applicationLink: 'https://coe-iot.com',
    isOfficial: true,
    officialSource: 'NASSCOM Center of Excellence (nasscom.in)',
    lastVerified: '2026-09-05',
    status: 'Active'
  },
  {
    id: 'sch_cgtmse_credit',
    name: 'CGTMSE Credit Guarantee Scheme for Micro & Small Enterprises',
    agency: 'Ministry of MSME & SIDBI',
    category: 'Collateral-Free Loans',
    fundingType: 'Debt / Working Capital',
    budget: 'Up to ₹2 Crore',
    fundingAmountNum: 20000000,
    sector: 'All Commercial & Manufacturing',
    stage: 'TRL 7 - TRL 9 (Commercial Scale)',
    eligibility: 'DPIIT recognized startups and Udyam-registered MSMEs seeking bank loans without third-party guarantee or collateral.',
    benefits: 'Credit guarantee coverage up to 85% for loans up to ₹200 Lakhs through scheduled commercial banks at subsidized interest.',
    deadline: 'Rolling Window (Open Year-Round)',
    applicationLink: 'https://www.cgtmse.in',
    isOfficial: true,
    officialSource: 'Credit Guarantee Trust for MSEs (cgtmse.in)',
    lastVerified: '2026-09-12',
    status: 'Active'
  },
  {
    id: 'sch_ip_patent_rebate',
    name: 'Patent & Trademark FastTrack SIPP Scheme',
    agency: 'Controller General of Patents, Designs and Trade Marks (CGPDTM), DPIIT',
    category: 'IP Support & Regulatory Rebates',
    fundingType: 'Fee Reimbursement',
    budget: 'Up to ₹2 Lakhs per Domestic Patent',
    fundingAmountNum: 200000,
    sector: 'Intellectual Property Protection',
    stage: 'Any TRL (Patent Pending or Drafted)',
    eligibility: 'DPIIT-certified startups filing national or PCT patent applications with Indian priority dates.',
    benefits: '80% fee rebate on statutory patent filings; government-empaneled patent facilitators provide zero-charge professional filing.',
    deadline: 'Open Year-Round',
    applicationLink: 'https://ipindia.gov.in',
    isOfficial: true,
    officialSource: 'Intellectual Property India (ipindia.gov.in)',
    lastVerified: '2026-08-15',
    status: 'Active'
  },
  {
    id: 'sch_meity_tide',
    name: 'MeitY TIDE 2.0 (Technology Incubation & Development)',
    agency: 'Ministry of Electronics and Information Technology (MeitY)',
    category: 'Incubation & Seed Grants',
    fundingType: 'Grant & Equity',
    budget: 'Up to ₹40 Lakhs',
    fundingAmountNum: 4000000,
    sector: 'Electronics, IoT, AI, Cybersecurity',
    stage: 'TRL 4 - TRL 7',
    eligibility: 'Tech startups incubated at MeitY supported G1/G2/G3 academic incubators developing solutions for national digital stack.',
    benefits: 'Entrepreneur-in-Residence (EiR) fellowship of ₹4 Lakhs + Seed grant support up to ₹40 Lakhs with lab testing.',
    deadline: '2026-11-20',
    applicationLink: 'https://tide.meity.gov.in',
    isOfficial: true,
    officialSource: 'MeitY Startup Hub (meity.gov.in)',
    lastVerified: '2026-08-30',
    status: 'Active'
  }
];

export const GOVERNMENT_SCHEMES = [
  {
    id: 'gov_sch_01',
    name: 'Maharashtra Digital Hospital Diagnostic Sandbox Grant 2026',
    department: 'Public Health Department, Govt of Maharashtra',
    sector: 'HealthTech',
    budget: '₹4.5 Cr',
    budgetNum: 45000000,
    fundingType: 'Sandbox Pilot Grant + Procurement Pipeline',
    stage: 'TRL 7+',
    eligibility: 'DPIIT recognized startups with CDSCO/ISO 13485 compliant AI medical diagnostic screening algorithms.',
    benefits: 'Full funding for 90-day sandbox deployment at 5 district hospitals, cloud compute subsidy, and GFR 149 scale order.',
    deadline: '2026-10-30',
    applicationLink: '/schemes-opportunities?apply=gov_sch_01',
    status: 'Published',
    applicationsReceived: 14,
    startupsParticipating: 3,
    outcomes: '14,280 patient screenings validated with 96.4% diagnostic accuracy.',
    isOfficial: true,
    isDemo: true
  },
  {
    id: 'gov_sch_02',
    name: 'State Infrastructure Quality & Pothole Telemetry Challenge',
    department: 'Public Works Department (PWD)',
    sector: 'InfraTech & IoT',
    budget: '₹3.0 Cr',
    budgetNum: 30000000,
    fundingType: 'Field Trial Grant',
    stage: 'TRL 7+',
    eligibility: 'Startups with vehicle-mountable edge camera or LiDAR sensors for automatic road distress detection.',
    benefits: 'Deployment testing over 250 km of state highways, real-time GPS ticketing integration, and PWD vendor empanelment.',
    deadline: '2026-11-15',
    applicationLink: '/schemes-opportunities?apply=gov_sch_02',
    status: 'Published',
    applicationsReceived: 8,
    startupsParticipating: 2,
    outcomes: 'Testing in progress along Samruddhi Mahamarg corridor.',
    isOfficial: true,
    isDemo: true
  },
  {
    id: 'gov_sch_03',
    name: 'Smart Water Grid Acoustic Leak Detection Sandbox',
    department: 'Water Resources Department (Jal Jeevan)',
    sector: 'WaterTech',
    budget: '₹2.5 Cr',
    budgetNum: 25000000,
    fundingType: 'Municipal Sandbox Pilot',
    stage: 'TRL 6 - TRL 8',
    eligibility: 'IoT acoustic sensor and flow telemetry startups with zero-excavation pipe leak localization capabilities.',
    benefits: 'Live pipeline testing on municipal distribution network, municipal corporation co-funding, and commercial scale-up pipeline.',
    deadline: '2026-12-01',
    applicationLink: '/schemes-opportunities?apply=gov_sch_03',
    status: 'Published',
    applicationsReceived: 11,
    startupsParticipating: 2,
    outcomes: 'Leak localization response reduced from 48 hours to 15 minutes.',
    isOfficial: true,
    isDemo: true
  },
  {
    id: 'gov_sch_04',
    name: 'AI Micro-Climate Agriculture Pest Warning Network',
    department: 'Agriculture Department',
    sector: 'AgriTech',
    budget: '₹2.0 Cr',
    budgetNum: 20000000,
    fundingType: 'R&D Grant + Field Deployment',
    stage: 'TRL 6+',
    eligibility: 'Startups with automated weather-pest sensor traps and vernacular SMS alert engines for smallholder farmers.',
    benefits: 'Sandbox deployment across 12 Krishi Vigyan Kendras (KVKs), field testing with 5,000 farmers, and district scale orders.',
    deadline: '2026-11-30',
    applicationLink: '/schemes-opportunities?apply=gov_sch_04',
    status: 'Published',
    applicationsReceived: 6,
    startupsParticipating: 1,
    outcomes: 'Field trials launched in Vidarbha and Marathwada blocks.',
    isOfficial: true,
    isDemo: true
  }
];

export const STARTUP_OPPORTUNITIES = [
  {
    id: 'opp_health_01',
    title: 'AI Diagnostic Screening for Rural Primary Health Centres (PHCs)',
    department: 'Public Health Department',
    sector: 'HealthTech',
    problem: 'Shortage of certified radiologists at 148 sub-district and rural PHCs leading to delayed diagnosis of pneumonia and pulmonary tuberculosis.',
    budget: '₹3.2 Cr Sandbox Allocation',
    budgetNum: 32000000,
    duration: '90 Days Sandbox Trial',
    requiredCapabilities: 'TRL 8+, Edge-computing inference (no cloud dependency), ISO 13485 certification, DPDP Act 2023 compliance.',
    status: 'Pilot Running',
    applicantsCount: 6,
    shortlistedStartup: 'HealthAI Technologies Pvt Ltd',
    district: 'Pune (Aundh District Hospital)',
    isDemo: true
  },
  {
    id: 'opp_pwd_02',
    title: 'Automated Road Surface Distress & Pothole Telemetry',
    department: 'Public Works Department (PWD)',
    sector: 'InfraTech',
    problem: 'Manual road condition surveys cause months of delay in pothole resurfacing and budget leakage on state highways.',
    budget: '₹2.1 Cr Sandbox Allocation',
    budgetNum: 21000000,
    duration: '60 Days Field Trial',
    requiredCapabilities: 'High-speed camera telemetry (>60 km/h), sub-meter GPS accuracy, automated PWD work-order generation.',
    status: 'Evaluation Gate',
    applicantsCount: 4,
    shortlistedStartup: 'RoadVision Edge Labs',
    district: 'Nashik & Chhatrapati Sambhajinagar',
    isDemo: true
  },
  {
    id: 'opp_water_03',
    title: 'Acoustic Pipeline Leak Detection & Water Balance Telemetry',
    department: 'Water Resources Department',
    sector: 'WaterTech',
    problem: 'Non-revenue water (NRW) loss exceeds 34% due to undetected subterranean distribution pipeline cracks.',
    budget: '₹1.8 Cr Trial Budget',
    budgetNum: 18000000,
    duration: '90 Days Trial',
    requiredCapabilities: 'Acoustic frequency analysis, IoT LoRaWAN / 4G battery-operated edge sensors, GIS dashboard sync.',
    status: 'Open for Proposals',
    applicantsCount: 5,
    shortlistedStartup: 'Pending Committee Selection',
    district: 'Nagpur & Amravati',
    isDemo: true
  },
  {
    id: 'opp_forest_04',
    title: 'IoT Early Wildfire Alert & Drone Sentinel Network',
    department: 'Environment & Forest Department',
    sector: 'GreenTech & Drones',
    problem: 'Delayed detection of crown fires in dense Western Ghats reserves causing biodiversity loss and ranger endangerment.',
    budget: '₹2.0 Cr Allocation',
    budgetNum: 20000000,
    duration: '120 Days Pilot',
    requiredCapabilities: 'Optical and infrared thermal sensors, autonomous long-range VTOL drone patrol, solar edge stations.',
    status: 'Open for Proposals',
    applicantsCount: 3,
    shortlistedStartup: 'Pending Committee Selection',
    district: 'Satara & Kolhapur',
    isDemo: true
  }
];

export const SUCCESS_STORIES = [
  {
    id: 'succ_01',
    startupName: 'HealthAI Technologies Pvt Ltd',
    solutionName: 'PulmoEdge AI Diagnostic Suite',
    department: 'Public Health Department, Govt of Maharashtra',
    district: 'Aundh District Hospital, Pune',
    pilotDuration: '90 Days Sandbox Trial',
    impactMetrics: [
      { label: 'Screenings Completed', value: '14,280 patients' },
      { label: 'Diagnostic Concordance', value: '96.4% accuracy' },
      { label: 'Triage Time Saved', value: '42 mins / patient' },
      { label: 'Commercial Order', value: '₹3.2 Cr (36 Districts)' }
    ],
    procurementAward: 'Awarded commercial contract under GFR Rule 149 Innovation Exemption after zero false-negative clinical audit.',
    quote: 'GovScale allowed us to test our clinical AI in a real government district hospital with cryptographic telemetry backing every screening. The direct commercial scaling under GFR 149 transformed our startup.',
    founder: 'Dr. Vikram Anand, MD & Founder',
    isVerified: true
  },
  {
    id: 'succ_02',
    startupName: 'RoadVision Edge Labs',
    solutionName: 'RoadVision IoT Sensor Rig',
    department: 'Public Works Department (PWD)',
    district: 'Samruddhi Mahamarg Corridor',
    pilotDuration: '60 Days Field Telemetry',
    impactMetrics: [
      { label: 'Highway Audited', value: '250 km stretch' },
      { label: 'Potholes Tagged', value: '3,120 defects' },
      { label: 'Survey Speed', value: '65 km/h live inference' },
      { label: 'Savings Generated', value: '₹4.5 Cr in prevented damage' }
    ],
    procurementAward: 'Empaneled across 4 PWD divisions for ongoing algorithmic highway quality compliance.',
    quote: 'Instead of waiting 2 years for traditional tenders, we completed our field trial in 60 days with telemetry verified directly on the state blockchain.',
    founder: 'Neha Deshmukh, Chief Technology Officer',
    isVerified: true
  }
];

export const INITIAL_STARTUP_APPLICATIONS = [
  {
    id: 'app_sch_901',
    schemeOrOppId: 'gov_sch_01',
    title: 'PulmoEdge AI Diagnostic Screening Deployment',
    startupId: 'usr_startup_01',
    startupName: 'HealthAI Technologies Pvt Ltd',
    dpiitId: 'DPIIT-89241',
    department: 'Public Health Department',
    sector: 'HealthTech',
    budgetQuote: '₹3.2 Cr',
    timeline: '90 Days Sandbox Pilot',
    trlLevel: 'TRL 8 (Flight/Field Qualified)',
    status: 'Active', // Draft, Submitted, Under Review, Selected, Active, Completed, Rejected
    solutionFit: 'Autonomous x86 edge diagnostic algorithm designed specifically for rural PHC X-ray machines with zero internet requirement.',
    capabilityProof: 'ISO 13485 medical device certificate, CDSCO clinical trial clearance, 14,280 screening test log.',
    submittedAt: '2026-09-08',
    governmentFeedback: 'Clinical audit passed with 96.4% concordance. Qualified for commercial scaling under Rule 149 GFR.',
    aiMatchScore: 96,
    aiMatchReason: 'Matches Public Health criteria on zero-cloud edge hardware, clinical TRL-8 certification, and DPDP 2023 compliance.'
  },
  {
    id: 'app_sch_902',
    schemeOrOppId: 'opp_pwd_02',
    title: 'RoadVision Edge AI Pothole Detection',
    startupId: 'usr_startup_01',
    startupName: 'HealthAI Technologies Pvt Ltd',
    dpiitId: 'DPIIT-89241',
    department: 'Public Works Department (PWD)',
    sector: 'InfraTech',
    budgetQuote: '₹2.1 Cr',
    timeline: '60 Days Field Trial',
    trlLevel: 'TRL 7 (Operational Prototype)',
    status: 'Under Review',
    solutionFit: 'Mountable vehicle sensor boxes with real-time computer vision inference streaming defect tickets to PWD GIS servers.',
    capabilityProof: 'Tested on 250km Samruddhi Mahamarg corridor with 93.2% distress detection.',
    submittedAt: '2026-09-14',
    governmentFeedback: 'Under committee review for technical feasibility and sensor mounting safety on state inspection vehicles.',
    aiMatchScore: 91,
    aiMatchReason: 'Strong algorithmic match for PWD automated ticketing; hardware vibration damping under evaluation.'
  }
];

export const IMPACT_METRICS = {
  totalSchemesValue: '₹48.5 Cr',
  totalSchemesCount: 16,
  startupsConnected: 184,
  applicationsReceived: 426,
  approvedProposals: 38,
  pilotSuccessRate: '92.4%',
  estimatedProcurementValue: '₹34.2 Cr',
  districtsCovered: '36 / 36',
  departmentsInvolved: 8
};
